DWAPlannerROS:

  max_vel_x: 0.5
  min_vel_x: 0.0

  max_vel_theta: 1.0
  min_vel_theta: 0.3

  acc_lim_x: 1.0
  acc_lim_theta: 2.0

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  sim_time: 2.0
  vx_samples: 20
  vtheta_samples: 40

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05
