use_map_topic: true
first_map_only: false

min_particles: 300
max_particles: 1500
kld_err: 0.05
kld_z: 0.99

update_min_d: 0.2
update_min_a: 0.1

resample_interval: 1
transform_tolerance: 0.2
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# ── Laser model ───────────────────────────────────────
laser_min_range: 0.1
laser_max_range: 6.0
laser_max_beams: 60

laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1

# ── Odometry model ────────────────────────────────────
odom_model_type: diff

odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1
