global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0

resolution: 0.05
transform_tolerance: 0.3

obstacle_range: 3.0
raytrace_range: 3.5

inflation_radius: 0.55
cost_scaling_factor: 10.0

observation_sources: laser_scan

laser_scan:
  sensor_frame: laser
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
